version: '3'
services:
  pinito-db:
    image: postgres:13
    env_file:
      - ./data/.env
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/00-database.sql:/docker-entrypoint-initdb.d/00-database.sql
      - ./data/01-records.sql:/docker-entrypoint-initdb.d/01-records.sql
      - ./data/02-triggers.sql:/docker-entrypoint-initdb.d/02-triggers.sql
    networks:
      - pinitonet
  pinito-pgadmin:
    image: dpage/pgadmin4
    container_name: mypgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pinitoprueba@yopmail.com
      PGADMIN_DEFAULT_PASSWORD: P1niT0
    ports:
      - "5050:80"
    networks:
      - pinitonet
  pinito-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    networks:
      - pinitonet
  pinito-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    container_name: frontend
    restart: always
    ports:
      - 80:80
    networks:
      - pinitonet

networks:
  pinitonet:
    driver: bridge